# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

inhibit_all_warnings!

target 'SBDebug' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SBDebug
  pod 'Starscream'
  pod 'SwiftyJSON'
  pod 'ReachabilitySwift'
  pod 'NetUtils'
  pod 'SwiftHash'
  pod 'SwiftHTTP'

end
